### ISSUE TITLE
A direct chat doesn't jump on the top when sending a message from mobile

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#138]
# Actual Result
When sending a message from mobile, the direct chat doesn't jump to the top of direct messages and doesn't update the last message time.
![image](https://user-images.githubusercontent.com/69950655/103279812-494ae580-4a01-11eb-997f-af94435a35d0.png)
![image](https://user-images.githubusercontent.com/69950655/103279836-5ec00f80-4a01-11eb-8384-ad9b13e61c4d.png)

# Expected Result
The direct chat should be shown on top, and time should be updated

# Environment
Both Android and iOS app

**Comment by bobs4462** [comment]
Ok, will look into and see what i can do.

**Comment by tlle14** [comment]
Hi @bobs4462 
I don't see the change after refactoring. Please fix this issue. 
https://images.zenhubusercontent.com/309637937/54723877-0161-42df-bfc2-9ec570f56ca8/videoc4af6de0_4b1f_48c3_989f_b2be6960c99avideo.mp4

**Comment by bobs4462** [comment]
Yes, it seems that it's broken again, because we lost the last activity information from API.
We'll try to retrieve it again by other means, I'll solve the issue in conjunction with #139

**Comment by bobs4462** [comment]
@tlle14 Hello, the issue seems to fixed in production environment (chat.twake.app or http://35.180.119.32:3124 proxy). Can you give it another try, please. Thanks.

**Comment by tlle14** [comment]
It is quite inconvenient to test on production. 
And yes, the issue seems doesn't appear on Production. 
But on QA environment:
-  the direct chat doesn't jump to the top
- No highlight for the new message 
- The current timestamp is always updated for the top direct chat 
https://images.zenhubusercontent.com/309637937/9e998377-1fe6-4527-b599-809d4c04bcb2/rpreplay_final1614589272.mp4

**Comment by bobs4462** [comment]
@RomaricMourgues can you please clarify this thing, is the web.qa.twake.app behind the chat.twake.app? Because in chat.twake.app the last_activity property of channels (public/directs) are updated correctly after any activity, but on web.qa.twake.app last_activity doesn't change and seems to be lagging from actual activity for weeks.

**Comment by RomaricMourgues** [comment]
Can you try again ? It was an issue with the database I fixed on prod but not on QA

**Comment by bobs4462** [comment]
Oh, it worked, now last_activity properties seem to be updating correctly on both PROD and QA, thanks :)

**Comment by tlle14** [comment]
Hi @bobs4462 
The direct chat doesn't jump to the top when the user received new messages.

https://images.zenhubusercontent.com/309637937/4a87a481-00b4-44e8-9da0-9f15d26bbff8/video32720b1b_81c9_45cf_8adc_562e6cc0d5f8video.mp4

**Comment by tlle14** [comment]
Hi @bobs4462 

- When another user sends a message to the current user, the direct message jumps on top: Retest passed!
https://images.zenhubusercontent.com/309637937/a72fd841-d3f9-4054-81d4-3112ccbcc832/videobc93dd3c_d01c_4bc3_8b28_aa549d4d9922video.mp4

- When the current user sends a message to another member, the direct doesn't jump on top. User need to refresh to see the change
=> Expect: The direct should jump on top without needing to refresh the app
https://images.zenhubusercontent.com/309637937/57b868e8-bc75-4cf7-96e0-908c235aeb69/video7cb68933_0483_41ba_a135_b600b8c9c060video.mp4

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/06fe5748-3c69-45a3-8843-1b83ce6b472c/rpreplay_final1615954231.mp4

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass
https://images.zenhubusercontent.com/309637937/06fe5748-3c69-45a3-8843-1b83ce6b472c/rpreplay_final1615954231.mp4
