### ISSUE TITLE
iOS > The emoticon on iOS is partial hidden 

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#144]
# Actual Result
When opening a keyboard or tap on the emoticon, it displays a little part that will hide the bottom of the emoticon
![image](https://user-images.githubusercontent.com/69950655/103341398-6a6f0d00-4ab9-11eb-8e8f-786a4c609db5.png)

# Expected Result
The emoticon shouldn't be hidden

# Environment
iOS app only

**Comment by bobs4462** [comment]
Seems to be an adaptiveness issue, will look into it

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/15267635-eb65-4bcd-ab6f-550de7ac7a2b)

**Comment by tlle14** [comment]
Sorry for my mistake. 
The issue is not passed on iOS. 
The last confirmation is on Android. 
![image](https://user-images.githubusercontent.com/69950655/106716141-a5241200-6630-11eb-9613-8a0e49191fbd.png)

**Comment by tlle14** [comment]
Hi @RockinPaul 
Retest failed on twake.2.2.7

![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/85cec9de-051d-41ed-a5bb-779466bf91e1)

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/1c5b1648-ee1f-4902-9ed1-3bb893b5c8ce)
