### ISSUE TITLE
A messages cannot display instantly between Mobile Devices

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#150]
# Precondition
Sending a message from iPhone App to Android App

# Actual Result
When sending messages between mobile devices, the messages are not displayed instantly

# Expected Result
The messages sending between mobile devices should display instantly

# Environment
Both Android and iOS devices

**Comment by tlle14** [comment]
@bobs4462 please take a look at this issue. It should be fixed soon.

**Comment by bobs4462** [comment]
I know I know, but it's not totally up to us, we are waiting still for working notifications, which haven't been rolled out to beta.twake.app (production) yet.

**Comment by bobs4462** [comment]
Hi @tlle14, we implemented message sync, but it currently requires active internet connection (obviously :)) and it only works on a workspace level, that means that if you were to switch workspace or company, you will loose the sync. But for the open workspace the sync works now, not perfectly though but it works.

**Comment by tlle14** [comment]
@bobs4462 
Retest failed!
Sending between android and ios devices isn't successful.

- Not in the real-time
- Displays only when pull to refresh the App.

**Comment by bobs4462** [comment]
We tested it in iOS emulator to Android emulator, and iOS device to Android device, the realtime sync in one workspace seems to be working correctly, can you retest it again?

**Comment by tlle14** [comment]
Hi @bobs4462 
I tested in the unstable network connection so the app became unstable too, as describe in this ticket: 
https://github.com/Twake/Mobile/issues/303

Let me retest when the internet connection becomes more speedy

**Comment by tlle14** [comment]
Retest pass on 2.2.9 with the stable network connection
