### ISSUE TITLE
Channel list > Incorrect time displays in the channel list

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#177]
# Actual Result
The last message's time is incorrect in the channel list/ direct chat list.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9d5a131c-4e90-4628-87c9-aa7f7d57ff95)

While in the message:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/1494022a-d1e5-419f-b2d5-b668ce61ddba)

# Expected Result
The time should be correct in the channel list/ direct chat list

**Comment by romanesko** [comment]
@bobs4462 Now timestamps are in ms, please fix in app

**Comment by bobs4462** [comment]
@romanesko It doesn't work as expected, dates are not updated right after sending the message to the channel

**Comment by romanesko** [comment]
fixed

**Comment by tlle14** [comment]
Thank @romanesko 
The time is correct now
https://images.zenhubusercontent.com/309637937/7a4cecfb-a255-4e74-888f-2686f4db6adf/video0cbbd3ca_a2ff_4c07_87f7_1522080daa6bvideo.mp4
