### ISSUE TITLE
Create Channel > Selecting channel icon button doesn't work

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#182]
# Actual Result
When creating a channel, the select icon button doesn't work
https://user-images.githubusercontent.com/69950655/104994917-fab8c600-5a57-11eb-889b-4aed931ce009.mp4

# Expected Result
When tapping on the select icon button, it should display an emoji keyboard for choosing the channel icon. 
There should have a default icon as on Web App.
![image](https://user-images.githubusercontent.com/69950655/104995053-394e8080-5a58-11eb-96e3-e57bffef6e23.png)

# Environment
Android mobile
Build version: twake.2.1.0

**Comment by RockinPaul** [comment]
The icon button is temporarily removed from this screen since we have no corresponding API for its implementation.

**Comment by tlle14** [comment]
Hi @RockinPaul 
I think we should remind @RomaricMourgues to work on this API, or we don't have that feature on the mobile app.
Let's move this issue to the icebox column.

**Comment by RomaricMourgues** [comment]
We do have an api for this, you only need to set { "icon": "🚴‍♀️" } in the channel object when creating / updating it :)

**Comment by tlle14** [comment]
@RockinPaul: Babur removed the emoji keyboard so we cannot select an icon for a channel. Could you please confirm? @bobs4462 ?

**Comment by bobs4462** [comment]
> We do have an api for this, you only need to set { "icon": "🚴‍♀️" } in the channel object when creating / updating it :)

@RomaricMourgues we used to have emoji short names in icons, not their utf representation. Has this behavior changed in new API?

**Comment by bobs4462** [comment]
> @RockinPaul: Babur removed the emoji keyboard so we cannot select an icon for a channel. Could you please confirm? @bobs4462 ?

Yes for now we searching for better solution, we might take existing emoji picker library and modify them to our needs, but we also should make sure all the emoji that are present in chosen library are supported by twake

@RomaricMourgues What would you suggest we do, about this emoji compatibility thing?

**Comment by RomaricMourgues** [comment]
I suggest we go with default emojis in UTF-16 format, before we where using :emoji-name: format but as this is not consistant, lets continue with simple UTF-16 (default emoji font).

So instead of sending :smile: we send 😃 directly.

That said, you should be able to use any emoji provider.

**Comment by tlle14** [comment]
It works on 2.2.9-2
