### ISSUE TITLE
Cannot delete a message

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#201]
# Actual result
Cannot delete a message
https://user-images.githubusercontent.com/69950655/105164835-35019080-5b48-11eb-8284-fbf6e71a3eca.mp4

# Expected Result
It should be able to delete a message successfully

# Environment
Android mobile
Build version: twake.2.1.1

**Comment by tlle14** [comment]
Thank @romanesko and @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/5ae5813f-ffdd-41ea-8730-00d6e38109a7/video7390de51_a422_4679_a0fd_268139a937ccvideo.mp4

**Comment by tlle14** [comment]
We can normally delete a message. But with the new message, we cannot delete them at the 1st time. 
The issue might relate to https://github.com/TwakeApp/Mobile/issues/255

**Comment by bobs4462** [comment]
Yes, I see, thank you @tlle14, we can reproduce the issue with newly sent messages. We're working on fixing this nasty bug :hammer_and_wrench:

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
Seems fast enough to be acceptable - able to delete a message after 1s
