### ISSUE TITLE
Notifications are broken on beta.twake.app

### ISSUE THREAD

**Issue by bobs4462** [Twake/Mobile#202]
Currently notifications are received by the application, but they contain no information whatsoever 
Here's an example.

```{notification: {title: null, body: null}, data: {notification_data: null}}```

**Comment by RomaricMourgues** [comment]
Currently working on this here: https://github.com/TwakeApp/Twake/issues/717 <https://github.com/TwakeApp/Twake/issues/717>

Should be good for end of week (sorry I have plenty of meetings)

Romaric

**Comment by bobs4462** [comment]
@RomaricMourgues, when do you plan to roll out the notifications on beta.twake.app, you said it's already available on qa...

**Comment by bobs4462** [comment]
And by the way has the bug with wrong UUID (where channel ids were wrong, there was 1 instead of 4 in 14th position) has been fixed?

**Comment by RomaricMourgues** [comment]
We are doing the OVH migration, beta.twake.app will not be changed until we finish this I'm sorry :/
For UUID, it should be fixed yes also on qa.

**Comment by bobs4462** [comment]
Ok thanks, can you please give me an approximate timeline, when we should expect notifications to be rolled out to beta.twake.app?

**Comment by RomaricMourgues** [comment]
Currently we are looking to the 14 of February deadline.

**Comment by bobs4462** [comment]
Great, thank you once more :) :+1:
