### ISSUE TITLE
UI > Workspace list design comparison

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#214]
# Actual Result
1. Recently, the app doesn't display the unread message counter 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/48dbae03-a341-4a18-ada5-bdf7ab014646)

2. Displaying the number of members below the workspace name
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/83e705ad-1560-4ba0-866b-7d832de8e4f2)
# Expected Result
Please confirm if we decide to follow the design. 
1. If yes, the unread message counter should display for the corresponding workspace on the sidebar
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/ab3437a6-770b-4109-bb08-af787b5dc525)

2. Below the workspace name, it should display the company name as design.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/03c7570b-8ea6-4d43-af4c-2cb4d30e1195)

**Comment by bobs4462** [comment]
@romanesko do we have an access to unread messages count for workspaces from api

**Comment by tlle14** [comment]
Hi @bobs4462 @romanesko
I updated the description. Please check

**Comment by bobs4462** [comment]
What's the point in displaying company name, if company name is always the same? :)

**Comment by romanesko** [comment]
@tlle14

**Comment by bobs4462** [comment]
Hi @tlle14 We added badges for unread counters, but as for the company name under workspace name, I think it's a bit irrelevant right now, because @BastiaanVanGaalen will completely overhaul the design soon anyway

**Comment by tlle14** [comment]
I can see the message counter on the workspace list now. Thank @bobs4462 
But the number is not correct. I should open another ticket.
