### ISSUE TITLE
UI > Channel list screen comparison

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#215]
### 1. The timestamp is displaying in the bold style
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/04c3f817-1cad-48ef-b63b-19289dd3ae03)

Expected Result
It should be in regular style as in the design
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/dedb3952-b37b-42b2-8796-9262eabbd2b3)

### 2. It displays a channel description below the channel name
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/5a292712-f210-4d05-9412-5447e36777dd)

Expected Result
It should display the preview of the latest message in a channel as in the design
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6fe85f2f-4e73-4b04-8ee3-b2cf003eaeda)

**Comment by bobs4462** [comment]
@BastiaanVanGaalen please can you confirm and approve that we implement those design features, or will the new design be completely different?

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 As for remarks given by @tlle14

**Comment by tlle14** [comment]
@bobs4462 @BastiaanVanGaalen 
If the last message preview the channel name, where the channel description will be displayed? In the channel screen, will replace the number of members in the channel?

**Comment by BastiaanVanGaalen** [comment]
@tlle14 This meta information such as channel photo viewing and description should be singled out onto a "channel details" screen.
I will implement this screen in further iterations.

**Comment by tlle14** [comment]
Thank @BastiaanVanGaalen 
So we decide to implement the current design and fix those UI issues as in the description.


> @bobs4462 As for remarks given by @tlle14 i confirm them as well for this iteration of the app
> 
> * timestamp in a regulat font style
>   -last message preview below the channel name
> 
> As for a new UI for now it's hard to say definitely that UI layout will stay the same.

**Comment by bobs4462** [comment]
@tlle14 Added last message preview to channels, but it only works for channels which had some activity since 15th of march.

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d2ce8a8a-1b73-4ea6-b431-53d7d7918302)
