### ISSUE TITLE
The message from Web app cannot be updated on Mobile App

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#220]
# Precondition 
Sending a message on the Web App

# Actual Result
The message cannot be automatically updated on the Mobile App
After pulling to refresh, the message isn't updated. User need to logout then login again to see the update.
https://images.zenhubusercontent.com/309637937/2c5623d5-4f83-425b-acaf-09722bb3a94b/videoc83096c9_b268_4b28_bdb6_f982217d071avideo.mp4

# Expected Result
The messages sent from the Web App should be automatically updated on Mobile App

# Environment
Android app
Build version: twake-2-2-0

**Comment by bobs4462** [comment]
@tlle14 can you give this issue a retest too?

**Comment by tlle14** [comment]
Hi @bobs4462 
Android still cannot get the message from web  instantly

**Comment by tlle14** [comment]
I close this issue because version 2.2.8 has the real-time update between web and mobile
