### ISSUE TITLE
Remove screen flicker when adding or removing messages

### ISSUE THREAD

**Issue by bobs4462** [Twake/Mobile#234]
In current implementation when adding or removing a message from the list, in order to immediately render the updated list we are forced to use keys on MessageTile widgets. But this approach has one unpleasant side effect - it forces the entire screen to be rerendered which causes it to flicker, which in turn negatively affects UX. We should investigate ways to add/remove messages and update the screen without forcing it to rerender everything.

**Comment by PokoinikRWS** [comment]
@RockinPaul / @romanesko next week

**Comment by tlle14** [comment]
Thank @bobs4462 and @RockinPaul 
Deleting a message have an issue, I'm not sure if it relates to this ticket
https://github.com/TwakeApp/Mobile/issues/261

**Comment by tlle14** [comment]
It seems no more issue
