### ISSUE TITLE
List of unread messages

### ISSUE THREAD

**Issue by romanesko** [Twake/Mobile#235]
Method with information about unread messages for the user.
Simply lists the messages (with  full info, workspace, channel, thread) that user haven't received yet.

**Comment by romanesko** [comment]
https://mobile.api.twake.app/documentation/static/index.html#/Messages/get_messages_whatsnew

GET /messages/whatsnew?company_id=<company_id>

@bobs4462 pls check and implement it if it's ok

**Comment by tlle14** [comment]
@bobs4462 I cannot test this implementation. 
Please review then close the ticket.

**Comment by tlle14** [comment]
Cannot test
