### ISSUE TITLE
Auto-transition to chat/channel right after its creation 

### ISSUE THREAD

**Issue by BastiaanVanGaalen** [Twake/Mobile#240]

**Comment by RockinPaul** [comment]
@romanesko Is it possible to obtain channel_id in the creation response? Right now I'm getting {success: true} and have no idea where to redirect a user.

**Comment by romanesko** [comment]
NP! Coming soon

**Comment by romanesko** [comment]
Done

**Comment by tlle14** [comment]
Thank @RockinPaul 
It almost works
https://images.zenhubusercontent.com/309637937/aef537d3-9c83-4b89-9c54-51a4078b4bda/rpreplay_final1613744429.mp4
