### ISSUE TITLE
Directs creation is broken

### ISSUE THREAD

**Issue by RockinPaul** [Twake/Mobile#246]
Direct creation request body: {company_id: 0e9337d6-54eb-11eb-9e45-0242ac120004, workspace_id: direct, name: , visibility: direct, icon: null, description: null, channel_group: null, default: true, **members: [156ad822-59b2-11eb-859c-0242ac120004]**}

Response: {id: 07c8b4aa-21a1-472e-821e-1408dedb8a22, name: , icon: , company_id: 0e9337d6-54eb-11eb-9e45-0242ac120004, workspace_id: direct, description: , channel_group: , **members: [291dae34-54ef-11eb-8031-0242ac120004]**, members_count: 1, last_activity: 0, messages_total: 0, messages_unread: 0}

Members are different.

**Comment by tlle14** [comment]
Thank @RockinPaul 
Seems it redirects to the correct member after got some cache issue. I will create another issue for this. 
https://images.zenhubusercontent.com/309637937/3b0d2c8b-e76c-43aa-8c75-9991eeca45a1/video60c22531_8d0d_4a05_8ca2_99b5da61a199video.mp4
