### ISSUE TITLE
Channel list > A private channel doesn't show the lock icon

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#248]
# Actual Result
There's no way for users to know if the channel is private.
![image](https://user-images.githubusercontent.com/69950655/106592828-92eb9a80-6582-11eb-9e40-20ef418c255e.png)

# Expected Result
The private channel should have something like a lock icon as on the Web Version
![image](https://user-images.githubusercontent.com/69950655/106592971-c75f5680-6582-11eb-8993-dd069a321ac0.png)

# Environment
iOS/Android App
Build version: twake.2.2.2

**Comment by BastiaanVanGaalen** [comment]
@tlle14 ok, we will add a lock icon. Thanks/

**Comment by tlle14** [comment]
Hi @RockinPaul 
I can see the lock icon for the private channel name. 
By the way, it seems not in the same line with the channel name.
Could you fix this small issue? 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/a0a5486f-6c6b-4403-a3bf-da5081354d61)

**Comment by tlle14** [comment]
Thank @RockinPaul 
The fix looks cool
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/14dd2957-4b75-474b-ac19-62298cc67d8a)
