### ISSUE TITLE
Emoji keyboard and the system keyboard are able to display at the same time

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#253]
# Actual Result

![8335E3C7-3859-49F9-8A68-D0782B30B387](https://user-images.githubusercontent.com/69950655/106699975-7731d400-6616-11eb-9c62-bc3d62623aca.jpg)

# Expected Result
They shouldn't display at the same time.

# Environment
Both android and ios devices
Build version: twake.2.2.2

**Comment by bobs4462** [comment]
Hi @tlle14, can you please tell us how did you achieve that? :)

**Comment by tlle14** [comment]
Hi @bobs4462 
Please refer to the video:

1. Tap to the chatbox
2. Change from the keyboard => Emoji keyboard
3. Tap and hold another message to reply to the message.
4. In the threaded replies screen, tap to chatbox
5. Tap to open the emoji keyboard 

https://user-images.githubusercontent.com/69950655/106712442-8bcc9700-662b-11eb-9687-5d9d8ef850fc.mp4

**Comment by tlle14** [comment]
Retest pass with emoji keyboard and the system keyboard.
Thank @bobs4462 
https://images.zenhubusercontent.com/309637937/7ade4a13-bea6-4eb5-bb50-003b2b8e85db/video5bfbd6b0_2288_4507_bf45_d9199dc613c9video.mp4


But could you please fix the system keyboard and the context menu? 
They shouldn't appear at the same time. 
The system keyboard will hide the context menu

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
The keyboard and the context menu cannot display at the same time.
The context menu will lay over the emoji keyboard when we open it.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/1f874f38-583d-4e11-b2b8-6efd240e86d4)
