### ISSUE TITLE
[Channel] Select private channel after click Create button then system auto display public room

### ISSUE THREAD

**Issue by hieuhoang998** [Twake/Mobile#254]
# Precondition
version:2.2.2 twake app
device: android: oppo reno 4 

1.Open twake app
2.Log in successfully
3.Select private channel 
4.Create channel

# Actual result
Display public room

# Expect result
Display private room

![processed (4)](https://user-images.githubusercontent.com/54783033/106713274-cbe04980-662c-11eb-8a70-73c18b9dcce6.jpeg)

![processed (5)](https://user-images.githubusercontent.com/54783033/106713292-d1d62a80-662c-11eb-8865-fbe6961916c5.jpeg)

**Comment by tlle14** [comment]
Retest pass!
Thank @RockinPaul 
https://images.zenhubusercontent.com/309637937/d2ec7a48-8757-4640-a18b-27b144cec056/rpreplay_final1613962426.mp4
