### ISSUE TITLE
App should recover itself when the internet connection back

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#263]
# Precondition
The internet connection is lost

# Actual Result
When the internet connection is back, the app doesn't recover itself. 
https://user-images.githubusercontent.com/69950655/106876641-82fec280-670a-11eb-9ea0-573cac6f3a92.mp4

# Expected Result
The app should be able to recover when reconnected to the server

**Comment by bobs4462** [comment]
@tlle14 Hello, can you give this issue another retest, I'm not sure I can reproduce the issue anymore ...

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/cf424d35-348f-493b-ac9e-2637cc9bd070/video39ae27e4_a75c_492e_9573_7526ae3c84d6video.mp4
