### ISSUE TITLE
Title bar in direct messages is broken

### ISSUE THREAD

**Issue by bobs4462** [Twake/Mobile#268]
Title bar which show the the names of participants in direct chat is not showing the any text. In debug mode, in throws an exception. 
![Screenshot_1613396942.png](https://images.zenhubusercontent.com/5f9ab4c67851dd4a461c956a/2410766c-6074-4d5f-ba8d-6e533bc4e606)

**Comment by tlle14** [comment]
Retest pass!
Thank @RockinPaul 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/249c2d24-ebe1-47a1-a282-9ad664f7fb61)
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/28995001-c776-4050-b9b9-c0cb08f31536)
