### ISSUE TITLE
Keyboard appearance on iOS.

### ISSUE THREAD

**Issue by RockinPaul** [Twake/Mobile#271]
The dark theme keyboard used while the main theme of the device is light. Android seems to be ok.

**Comment by tlle14** [comment]
Thank @RockinPaul 
Retest pass

**Enable Dark Theme**
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e22d7470-da97-49e3-937b-adca2c29ed93)


*Disable Dark Theme*
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/af2ba1da-757a-4f65-9b50-d29c943fa20a)
