### ISSUE TITLE
Notification >  the message cannot display after opened the push notification

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#289]
# Precondition
Sending a message with mentioning on Web App

# Actual Result
On Mobile, the user gets the push notification for the background running app. 
When he taps to the notification, it redirects to open the channel but the message doesn't display

https://user-images.githubusercontent.com/69950655/108999243-9df2a000-76d4-11eb-8789-09feca19c469.mp4

# Expected result
This issue might be related to syncing in the real-time issue between Web and Mobile
The message in the push notification should display when the user opens it. 

# Environment
Android App
Build version: twake.2.2.7

**Comment by bobs4462** [comment]
Can you try it again, it should work with active internet connection

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!

https://images.zenhubusercontent.com/309637937/086d8c70-9e9b-440a-8fe4-fab55d8e7272/rpreplay_final1615963556.mp4
