### ISSUE TITLE
Notification > When clear the push notification on notification panel, it also clears the badge icon counter 

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#290]
# Actual Result
When clear the notification on the notification panel, the badge icon counter also disappears.
https://user-images.githubusercontent.com/69950655/109001576-af897700-76d7-11eb-9044-3d80cd9bedc9.mp4

# Expected Result
The badge icon counter indicates the unread messages in the app. It shouldn't be cleared with the push notification.
It only disappears when the messages are read

# Environment
Android App
Build version: twake.2.2.7

**Comment by bobs4462** [comment]
@tlle14 Hello, I think that's the expected behavior for all the apps when you clear the notifications the badges are reset. I tested it on telegram and whatsapp

**Comment by tlle14** [comment]
> @tlle14 Hello, I think that's the expected behavior for all the apps when you clear the notifications the badges are reset. I tested it on telegram and whatsapp

Sorry @bobs4462 
I tested on iOS with Telegram and other chat apps.
On Android, I checked with Skype and it works like our current app. 
I should close the issue.
