### ISSUE TITLE
Channel title view isn't changing right after channel editing.

### ISSUE THREAD

**Issue by RockinPaul** [Twake/Mobile#292]

**Comment by tlle14** [comment]
Hi @RockinPaul 
The bug description is not clear. I don' get it. 
Is it about the screen after finish the channel updating? 
As I see, after finishing update a channel, it transit to a white screen
https://images.zenhubusercontent.com/309637937/eb49fcb3-89fe-4f2f-816f-6b6446e89173/rpreplay_final1614654335.mp4

**Comment by RockinPaul** [comment]
@tlle14 Yes, it's about updating metadata after return from the editing screen. Previously, it did not update the title of the channel properly and I've fixed it. But the behavior you attached in the video is something new and definitely deserves a new task.

**Comment by tlle14** [comment]
Thank you. I will create a new ticket for the bug. 
By the way, the change has been updated. I guess this issue is passed.
