### ISSUE TITLE
Server selection > Infinite loading when login with the non-existing server address

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#294]
# Precondition
Input the non-existing server address

# Actual Result
Log in with the non-existing server address, it displays the splash screen loading forever
https://images.zenhubusercontent.com/309637937/3949b161-3446-47e8-ae5d-6b6777820179/video996f984d_f99d_41a4_b190_573cea733a08video.mp4

# Expected Result
It should display an error message when the server is not found.

# Environment
iOS and Android App
Build version: twake.2.2.8

**Comment by tlle14** [comment]
Hi @bobs4462 
It takes time to return the response. Check this issue https://github.com/Twake/Mobile/issues/300

**Comment by tlle14** [comment]
Hello @bobs4462 
The infinite loading still happens on Android App.
- Server: https://mobile.api.twake - skip server verifying step
- Using a valid credential on QA environment to log in

https://user-images.githubusercontent.com/69950655/109593744-1ed1f180-7b44-11eb-9b8b-2be7cae4261b.mp4


=> It should return the error message about cannot find a server

**Comment by bobs4462** [comment]
@tlle14 Hi again, the issue seems to be related to recent issues with broken directs on web.qa.twake.app, so I cannot reproduce it now.

**Comment by tlle14** [comment]
Hi @bobs4462 
Could you please check? 
I don't see the response when login with an  invalid server address 
https://images.zenhubusercontent.com/309637937/b8d52d53-5cd7-4672-898d-db2dcc052b03/video1862edf5_a387_4a1a_9957_ce2d988ca4e8video.mp4

**Comment by bobs4462** [comment]
I couldn't reproduce it @tlle14, can you please check again?

**Comment by tlle14** [comment]
Thank @bobs4462 
It has an error message when login with an invalid host. But the message "Network error"  does not make sense. 
Please change the message content.
https://images.zenhubusercontent.com/309637937/f42936b9-4b06-4fd3-a375-683e6eb7f88e/video65978eb0_4b8a_4128_97ac_d9b2667e6759video.mp4

**Comment by bobs4462** [comment]
Changed the error text to **Server is unavailable**

**Comment by tlle14** [comment]
Hi @bobs4462 
It's still displaying invalid host, not `Server is unavailable`
It's ok when we use `invalid host` 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e62adea9-b688-43e6-95f5-5b5e9ee64b07)
