### ISSUE TITLE
Infinite loading when opening the push notification of the already logout account

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#309]
# Precondition
- UserA has push notifications in the notification center
- UserA has already logged out from Twake App
- UserB is logged in to the Twake App on the same phone
# Actual Result
When UserB opens the push notification of UserA, it redirects to the blank screen that loading infinitely. 
https://user-images.githubusercontent.com/69950655/109752122-66bf4a00-7c12-11eb-9023-4c4425b4f40c.mp4

# Expected Result
- It shouldn't display a badge counter for another account
- It should show a message to inform the user cannot open a push notification of another account

# Environment
Both iOS and Android app
Build version: 2.2.9

**Comment by bobs4462** [comment]
When user logs out, all notifications are cleared now, so this kind of situation should not happen

**Comment by tlle14** [comment]
Thank @bobs4462  for the solution.
Retest pass!
https://images.zenhubusercontent.com/309637937/1752a74b-6c8e-44c2-93be-3dc2fc384e52/video241f7cf2_85cc_4579_a766_6060996d949bvideo.mp4
