### ISSUE TITLE
Notification > Able to get push notifications of another account

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#319]
# Precondition
1. On Mobile:
- I used to log in to my Linagora account on the app (Production server)
- Currently, I log in as a member of another server (QA server )

2. On the web:
I also logged in 2 accounts in one browser, on different tabs.
![image](https://user-images.githubusercontent.com/69950655/109939187-63f05200-7d03-11eb-8bb0-28fa7a05fbf0.png)

# Actual Result
On mobile, I'm able to receive the push notification of another account

https://user-images.githubusercontent.com/69950655/109939385-9601b400-7d03-11eb-94aa-0f12cb0ce06d.mp4

# Expected Result
User shouldn't be able to receive a push notification of another account

# Environment
Android App and Web App
Build version: 2.2.9

**Comment by tlle14** [comment]
@RomaricMourgues @bobs4462 you guys should see this interesting issue

**Comment by RomaricMourgues** [comment]
Mmm this is a Twake web issue, and I can't solve it easily.
There is two things to ensure:
- Implement logout properly for us to delete device token (Please check on mobile side @bobs4462 )
- We should ensure unicity of token usage, two users cannot have the same device token (It's for us at Twake)
The critical bug is mainly on twake backend side so I will take care of it

**Comment by bobs4462** [comment]
@RomaricMourgues how should we notify the backend about logout fact, is there any method for that?

**Comment by RomaricMourgues** [comment]
Just post on "/ajax/users/logout" and pass the device id exactly like during login :)
```
{
  "device": {
    "type": "", //Always 'fcm' right now
    "value": "" //The token
  }
}
```

**Comment by bobs4462** [comment]
Great, thank :+1:

**Comment by bobs4462** [comment]
Hello @RomaricMourgues, I'm trying to call the method you gave me, and here is what I'm receiving 
```<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getId() on string in /twake-core/src/Twake/Users/Controller/UsersConnections.php:120
Stack trace:
#0 /twake-core/app/Common/BaseBundle.php(94): Twake\Users\Controller\UsersConnections-&gt;logout(Object(Common\Http\Request))
#1 /twake-core/app/Common/Routing.php(68): Common\BaseBundle-&gt;Common\{closure}(Object(Common\Http\Request))
#2 /twake-core/vendor/pecee/simple-router/src/Pecee/SimpleRouter/ClassLoader/ClassLoader.php(69): Common\Routing-&gt;Common\{closure}()
#3 /twake-core/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Route/Route.php(99): Pecee\SimpleRouter\ClassLoader\ClassLoader-&gt;loadClosure(Object(Closure), Array)
#4 /twake-core/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(397): Pecee\SimpleRouter\Route\Route-&gt;renderRoute(Object(Pecee\Http\Request), Object(Pecee\SimpleRouter\Router))
#5 /twake-core/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php(331): Pecee\SimpleRouter\Router-&gt;routeRequest()
#6 /twake-core/vendor/pecee/simple-router in <b>/twake-core/src/Twake/Users/Controller/UsersConnections.php</b> on line <b>120</b><br />
```

The request was made to htttps://web.qa.twake.app/ajax/users/logout, with `POST` method, the body of the request contained only this
```  
"device": {
    "type": "fcm",
    "value": "eXZsxaoZThO5v4_0nO0hrC:APA91bHlTu1Z7aFoo2zjbJ6Bl9akRY3ou9Qb5_1EoCOpil2787u3nU0DP0pY8cPkn0s2QMR4k0MAtVmlxspq6Cc75AKvPBpVPRE3FVwFDC4WAoH1YKN5_nIpMFX8KngpHBkvTcZbVWda",
    "version": "2020.Q3.107"
  }
```
The headers contained `Authorization: Bearer <some very long auth token>`

What I might be doing wrong?

**Comment by RomaricMourgues** [comment]
I look at this today

**Comment by RomaricMourgues** [comment]
It can only means the auth token isn't valid anymore, I added an ["error": "user disconnected"] response

**Comment by tlle14** [comment]
Thank @RomaricMourgues and @bobs4462 
Retest pass!
