### ISSUE TITLE
App doesn't display the unread message counter for channel and direct messages

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#324]
# Actual Result
When having a new message, channels and direct chats are bold, but no unread counter display.

# Expected Result
There should have an unread counter for the unread messages.

# Environment
Both android and iOS app
Build version: 2.2.9-1

**Comment by bobs4462** [comment]
@RomaricMourgues We used to have messages_unread property on channels to show the red badge, how can we get that value for channels again? Because now we are only getting has_unread flag.

**Comment by RomaricMourgues** [comment]
To check if there is unread messages (bold or not bold)
```
const unreadMessages =
    (channel.data.last_activity || 0) > (channel.data.user_member.last_access || 0) &&
    channel.data.last_message?.sender != channel.data.user_member?.user_id;
```

The badges are done by an other endpoint `/notifications/v1/badges/` you will get all badges in a company:
```
{
        company_id: companyId,
        all_companies: true,
},
```
Ex. **GET** /notifications/v1/badges/?company_id=xxx&all_companies=1 will return list of all badges for the requested company + one badge per other companies (to let now the user that there is notifications in other companies)

**Comment by tlle14** [comment]
Thank @bobs4462 
I can see the unread counter displays for channel and direct chat.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/7bec132b-97aa-4d28-bed9-c62d17b6de5f)
