### ISSUE TITLE
Notification > After the new message is read, push notification and badge counter don't disappear

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#328]
# Actual Result
When the user reads new messages without clicked the push notification, the push notification and badge counter are still displaying
https://images.zenhubusercontent.com/309637937/9621ce75-02c2-4fb0-8982-ad837b25f09a/videoa51a5da2_38a4_4374_81ea_7055a69d21f4video.mp4

# Expected Result
After the new messages are read, the badge counter and push notification should disappear

# Environment
Android app
Build version: 2.2.9-1

**Comment by bobs4462** [comment]
@tlle14 It's partially implemented now, meaning that the application can only track notifications which has been received in foreground. Those are tracked internally by application, and when user opens the channel, the notification is removed. As for the notifications which are received in background, those can be only removed in batch (all of them at once). 
I think you can test what is already there, and return ticket back, so we can think on how to control background notifications individually.

**Comment by tlle14** [comment]
Okay @bobs4462 
Thank for your explaination
