### ISSUE TITLE
Message > Cannot click the link in the message

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#33]
# Actual Result
Cannot click the link in the message
![image](https://user-images.githubusercontent.com/69950655/100983744-54366580-357c-11eb-96b6-8bf334921650.png)

# Expected Result
The user should be able to click the link in the message. It should open the link in the browser

# Environment
All Android devices

**Comment by bobs4462** [comment]
Added url launcher which will trigger the clicked link to opened in browser

**Comment by tlle14** [comment]
Thanks @bobs4462 
Retest pass!
https://streamable.com/nx8cuv

**Comment by tlle14** [comment]
Hello @bobs4462 
I reopen this issue because the retest failed on twake.2.2.3

https://user-images.githubusercontent.com/69950655/106889686-f3addb00-671a-11eb-91da-0698cf81f9a7.mp4

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass on twake.2.2.6 
https://images.zenhubusercontent.com/309637937/d5645010-14fe-4498-aeea-09bbcf3950b8/video5616a0c5_b164_4e16_b217_a78eaa15c96cvideo.mp4
