### ISSUE TITLE
Edit channel > Tap on avatar to open the emoji keyboard instead of "Change avatar" button

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#336]
# Actual Result
1. To open the emoji keyboard, the user needs to tap on the avatar in the circle
2. The channel icon is displaying smaller than the actual design
![image](https://user-images.githubusercontent.com/69950655/110576295-1eb0a200-8193-11eb-93a6-c156d39db8e8.png)

3. Edit channel screen displays the enabled Save button as a default

# Expected Result
1. To open the emoji keyboard, the user needs to tap on the button "Change avatar"
2. The channel icon should be bigger for more visible
3. Edit channel screen should display disabled Save button as a default
![image](https://user-images.githubusercontent.com/69950655/110576443-5e778980-8193-11eb-9526-56a0aa1b1999.png)
# Environment
Android app
Build version: 2.2.9-1

**Comment by tlle14** [comment]
Sorry I combined 3 issues in a screen

**Comment by BastiaanVanGaalen** [comment]
@tlle14 thanks for your remarks!

@RockinPaul 
1. We should set tappable not only "Change avatar" but the image itself so tappable area will be bigger which is more convenient for users.
2. Since emoji size is defined by a font size, it has to be at least two times bigger. Before releasing the updated emoji icon size, please send me a screenshot.
3. Correct.

**Comment by tlle14** [comment]
Hi @RockinPaul 
# 1. Failed 
It seems tap on `Change avatar` doesn't open the emoji keyboard.

# 2. Pass
The channel icon seems nice. Cc: @BastiaanVanGaalen 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f29a8732-46b3-4147-be33-d8cdbc4d07b6)

# 3. Failed
The `Save` button is still enabled
=> It should be displayed disable when there has nothing change

**Comment by tlle14** [comment]
Hi @RockinPaul 
Retest pass for change avatar function. 
We have a related issue but it should be another ticket

https://images.zenhubusercontent.com/309637937/20edc9a4-3e8b-4bbb-9c28-50bcf8df2a90/videof9976da0_3f89_49e9_877d_338da4e836d4video.mp4
