### ISSUE TITLE
Choose server > The default server is the old data

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#344]
# Actual Result
The default server is the old data
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/0fcdfdbe-087f-48a2-a7e5-7cc4fb7c9303)

# Expected Result
The default server should be our production address

# Environment
Both iOS and Android App
Build version: 2.2.9-2

**Comment by bobs4462** [comment]
@tlle14 Hello, yes it's going to be replaced in next build. But for now you can use both https://mobile.twake.app and https://mobile.api.twake.app to connect to production server, they both should work the same. So I don't see any point to keep this issue around.

**Comment by tlle14** [comment]
I see. Thank @bobs4462 for your explaination.
