### ISSUE TITLE
Some username are not displayed

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#346]
# Actual Result
Some usernames do not display on the Mobile app
On Web: 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/ebe514f9-0b66-4488-bc84-a84382049922)

On Mobile: 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d309b877-cd08-4a7e-bcbb-566d1feff625)

# Expected Result
Please investigate.
The username should display normally

# Environment
iOS App
Production server
Build version: 2.2.9-2

**Comment by bobs4462** [comment]
Hi @tlle14, can you please provide us with more information, did you find this bug in public channel, can we have access to it? Is it a single case, or have you encountered more bugs like this one?

**Comment by tlle14** [comment]
Hi @bobs4462 This issue is on production. Let me send you the message link on twake

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/acf58a5b-3ad9-4a9f-a64f-fd7d2636a209)
