### ISSUE TITLE
Cannot login successfully after edit server address

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#369]
# Actual result
After changing the server address from the incorrect to the right one, the user still cannot log in 
https://user-images.githubusercontent.com/69950655/111450714-3fed3180-8743-11eb-89e2-34fad4234f17.mp4

# Expected Result
The user should be able to login after switching to the correct server address

# Steps
1. Keep the production server address
2. Back to the login page, log in with a credential on QA environment.
There will have an error message display
3. Change the server address to the correct QA server
4. Continue login with the credential
- After the 1st tap, the error message displays. User cannot login.
- After the 2nd tap, the user is able to login. 

# Environment
- OS: both iOS and Android App
- Build version: 2.2.9-3

**Comment by bobs4462** [comment]
@tlle14 Can you run this test, again, neither me nor Pavel have been able to reproduce this issue...

**Comment by tlle14** [comment]
I can reproduce. But the loading screen keeps displaying forever.

**Comment by tlle14** [comment]
Well, it's not an issue when changing from QA address to the Production.

**Comment by bobs4462** [comment]
> I can reproduce. But the loading screen keeps displaying forever.

What kind of loading screen, the Twake logo or circular loader?

**Comment by tlle14** [comment]
> > I can reproduce. But the loading screen keeps displaying forever.
> 
> What kind of loading screen, the Twake logo or circular loader?

The twake logo @bobs4462

**Comment by tlle14** [comment]
Retest a bit on production
