### ISSUE TITLE
Channel > When open a channel, the icon is not fit

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#40]
# Actual Result
The channel icon is not fit
![image](https://user-images.githubusercontent.com/69950655/101000369-67533080-3590-11eb-9b3f-3c463340c5a3.png)

# Expected Result
The channel icon should be fit and display in the correct ratio.

# Environment
All Android devices

**Comment by bobs4462** [comment]
Implemented icon downscaling, should fix the issue.

**Comment by tlle14** [comment]
Retest pass
Thanks @bobs4462 
![image](https://user-images.githubusercontent.com/69950655/101347434-abaa3d80-38bc-11eb-8209-f6390bbfefac.png)

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue appears in the build version twake.2.2.2 

Please fix!

**Comment by bobs4462** [comment]
@RockinPaul Have you changed TextAvatar widget recently?

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/70daca94-02e4-4b9c-8b42-37357999aaca)
