### ISSUE TITLE
Channel > Incorrect number of members

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#41]
# Actual Result
Everyone in our workspaces can access the channel but it shows only 1 member.
![image](https://user-images.githubusercontent.com/69950655/101002617-a2eefa00-3592-11eb-9b4f-3fa54a7c7bb2.png)

# Expected Result
Should display the correct number of members in the channel

# Environment
All android devices

**Comment by bobs4462** [comment]
@romanesko I extract members count from members_count field in received json response.
Maybe the issue is on the api side.

**Comment by romanesko** [comment]
I'm translating it as is  ¯\_(ツ)_/¯

**Comment by tlle14** [comment]
Thank @bobs4462 and @romanesko 
Retest pass!
![Uploading image.png…]()

**Comment by hieuhoang998** [comment]
build version twake app 2.2.2

Hi, I see "0 member" in general please check it.
![processed](https://user-images.githubusercontent.com/54783033/106693698-9413da80-6609-11eb-9f64-3ff07a36af08.jpeg)

**Comment by romanesko** [comment]
it's fixed now

**Comment by tlle14** [comment]
Thank @romanesko 
Retest pass!
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/fb1760d6-2ee9-4d1a-854a-1cb923eb73f5)
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/59c02a23-5c00-4751-bfdc-44e7ebf07ad5)

**Comment by tlle14** [comment]
Hi @bobs4462 
I reopen this issue for it always shows `No members` in the channel
On Mobile: 
![image](https://user-images.githubusercontent.com/69950655/109779142-39859280-7c38-11eb-807a-6f252f7e86dc.png)

On Web: 
![image](https://user-images.githubusercontent.com/69950655/109779182-44d8be00-7c38-11eb-87df-45398f6516f6.png)

**Comment by tlle14** [comment]
Retest pass!
Thank @bobs4462 
https://images.zenhubusercontent.com/309637937/f878c503-0fdb-4955-bb48-de20bdd05dd5/rpreplay_final1616557242.mp4
