### ISSUE TITLE
The app should always have a real-time update

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#50]
# Actual Result
User needs to close the app or pull to refresh to get the newest update of the app (new messages, new channel, or direct chat...)

# Expected Result
The app should have a real-time update for all screens

# Environment
All android devices

**Comment by bobs4462** [comment]
We are currently working on notification system

**Comment by tlle14** [comment]
Hi @bobs4462 
has this one be implemented?

**Comment by bobs4462** [comment]
Hi @tlle14, no not yet, I'm actually not even sure whether we can completely sync the mobile with the web in the near future. Messages - yes, with the release of new API in the next month, messages should be kept in sync. The rest, like changing username or channel description, that might require some more time.

**Comment by tlle14** [comment]
Has the real-time update now
