### ISSUE TITLE
It always display a black screen flashly after user login to the app

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#68]
# Actual Result
When the user login to the app, it displays a black screen then redirects to the default workspace
https://streamable.com/jekt0v

# Expected Result
It shouldn't display a black screen. 
When the app is processing a login request, it should display a loading icon instead of moving to the new black screen. 
After login successfully, it should display a workspace screen.

# Enviornment
All Mobile devices

**Comment by tlle14** [comment]
Thank @romanesko and @bobs4462 
The screen is white looks unify with the app's theme.

**Comment by tlle14** [comment]
Hi @bobs4462 
I reopen this issue because it happens on Android Mobile

https://user-images.githubusercontent.com/69950655/110274122-afa34400-8000-11eb-9cbb-3e5ff68b5ca2.mp4

**Comment by bobs4462** [comment]
Restored Twake logo on splash screen for android

**Comment by tlle14** [comment]
Thank @bobs4462 
No more black screen but the splash doesn't fit the big screen size. Please tracking this issue here: https://github.com/Twake/Mobile/issues/367
