### ISSUE TITLE
App should have a response when losing internet connection

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#69]
# Actual Result
1. When logging into the app then the internet connection is lost, the app keeps displaying a loading screen (forever). Sometimes the user kills the app but cannot restart.
https://streamable.com/jdahoh

2. When there's no internet connection, sending a message or open a channel/direct will not successful but the app doesn't notify the user.

# Expected Result
- Request to the server should have timeout
- When there's no internet connection, the app should:
   + permanent displaying a message to notify on the top/bottom of the app
   + OR displaying a popup when having any request 

# Environment

**Comment by tlle14** [comment]
Hi @bobs4462 

# Actual Result
I can see the "No internet connection" warning when pulling to refresh or loading message.
But when sending a message when there is no internet connection, nothing happens.

# Expected Result 
When sending a message without an internet connection, it should display a warning popup for the user.

**Comment by tlle14** [comment]
Hi @bobs4462 

1. The app should have an internet connection warning when:
- reacting a message
- opening a thread
- deleting a message
- switching workspaces
- creating a channel
without internet.

2. The message should be the same in all actions: a text message, a popup, or a dialog.
3. The warning message should be placed where the user can easily see it.

Please work with our Designer and BA for a suitable solution.

**Comment by bobs4462** [comment]
@BastiaanVanGaalen Can you please provide us with one consistent design for this kind of warning messages? You can contact our colleagues from Vietnam if you need some additional info.

**Comment by BastiaanVanGaalen** [comment]
@bobs4462 Ok, i will implement this as well.

**Comment by BastiaanVanGaalen** [comment]
@RockinPaul 
Dev hand off: https://zpl.io/2pwyzkJ
When on direct messaging screen and there is no internet connection, right under the header yellow-coloured view with text and animated icon and rotating clock hand + below a timestamp there will be one more animated clock icon

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen 
Could you please invite me to the Zeplin project? I need to compare the app with the design.
Thank you!

**Comment by hieuhoang998** [comment]
Hi, This issue is fixed so I close this issue

**Comment by tlle14** [comment]
I reopen this issue because the warning message doesn't show when losing the internet connection
https://streamable.com/deghba

**Comment by bobs4462** [comment]
Hey, guys, can you retest this issue again?

**Comment by tlle14** [comment]
Thank @bobs4462 
There has a warning message when submitting a message without the internet connection
https://images.zenhubusercontent.com/309637937/2959e7cc-1731-4f68-b354-342a4d11317b/video39ae27e4_a75c_492e_9573_7526ae3c84d6video.mp4
