### ISSUE TITLE
Notification > Cannot redirect to the corresponding thread when tap to the notification

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#99]
# Actual Result
Tap to the notification on the Notification center, it redirects to the Twake app but doesn't open the corresponding thread 
https://streamable.com/0sz4zx

# Expected result
When user taps to the notification on Notification Center, it should redirect to the corresponding thread 

# Environment
app-release[2020-12-15].apk

**Comment by bobs4462** [comment]
@RomaricMourgues That's where the click_action at the highest level of data object comes handy)

**Comment by bobs4462** [comment]
Also, channel_id field provided in notification is wrong. We have a very strange behavior here:
For example user A navigates to channel acf640c2-1dcc-41eb-9aff-0242ac120004 and keeps it open. 
While the user B from desktop writes to this channel.
For the first message we are correctly notified, and pull the message and show it user.
But if the user B writes another message, the notification is sent, but it contains wrong channel_id, in our case acf640c2-1dcc-11eb-9aff-0242ac120004 (which almost identical).

It doesn't match the one that we are currently viewing.

**Comment by RomaricMourgues** [comment]
Ok this is our migration from uuidv1 to v4. I will not be able to fix this easily, can you put a monkey fix for now ?

On the __old channel API__ replace X in channel_id by a 1 if it's a 4.
aaaa0000-aaaa-Xaaa-aaa-0000aa000000

**Comment by bobs4462** [comment]
wow, that's truly a monkey patch :). Ok, i'll patch it that way temporarily

**Comment by bobs4462** [comment]
The wrong channel_id is fixed. But still the problem with click_action not being on the highest level of data object prevents from handling clicks correctly.

**Comment by RomaricMourgues** [comment]
Fixing click_action on production is too dangerous, I need to change the libraries we use.
So we'll have this only in QA and from the next production update :/

**Comment by bobs4462** [comment]
Ok, I understand, thanks :)

**Comment by bobs4462** [comment]
@RomaricMourgues when can we move **click_action** field to the top of data structure of notification?

**Comment by RomaricMourgues** [comment]
As soon as issue #717 ( https://github.com/TwakeApp/Twake/issues/717 ) is done :)
Should be in two weeks max

**Comment by tlle14** [comment]
Hi @bobs4462 
I don't think this feature works on twake.2.2.7
Please investigate!

**Comment by bobs4462** [comment]
@tlle14  Do you mean that you don't get navigated, or you don't get any notifications?

**Comment by tlle14** [comment]
@bobs4462 I cannot get any notifications.

**Comment by bobs4462** [comment]
Even mentions? like ```@babur hello it's me```

**Comment by tlle14** [comment]
Now I can get the notification. 
And this case is passed on Android only. I cannot see the notification on iOS

https://user-images.githubusercontent.com/69950655/108486723-f7bc2a00-72d0-11eb-9a20-716618cf4e12.mp4

**Comment by tlle14** [comment]
Hi @bobs4462 
I reopen this issue for iOS notification

**Comment by tlle14** [comment]
Thank @bobs4462 
Retest pass!
https://images.zenhubusercontent.com/309637937/539fa4e2-c7e1-4eef-8554-383e66b0ebfb/rpreplay_final1615457961.mp4
